{% set version = "1.1.0" %}

package:
  name: pamela
  version: {{ version }}

source:
  fn: pamela-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pamela/pamela-{{ version }}.tar.gz
  md5: 282516018839cda3a46d59fb2a71db4e

build:
  number: 0
  noarch: python
  script: pip install --no-deps .

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - pamela

about:
  home: https://github.com/minrk/pamela
  license: MIT
  license_file: COPYING
  summary: PAM interface using ctypes

extra:
  recipe-maintainers:
    - minrk
