{% set version = "1.2.0" %}

package:
  name: pamela
  version: {{ version }}

source:
  fn: pamela-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pamela/pamela-{{ version }}.tar.gz
  md5: 37d71159f1bc17009ff568fd919c2a4d

build:
  number: 0
  noarch: python
  script: pip install --no-deps .

requirements:
  host:
    - python
    - pip

  run:
    - python >=3.5

test:
  imports:
    - pamela

about:
  home: https://github.com/minrk/pamela
  license: MIT
  license_file: COPYING
  summary: PAM interface using ctypes

extra:
  recipe-maintainers:
    - minrk
