# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lmpPcmLasGl8xOQhNuqtIx+8XLhvLdJs16VhUlLjfw8lnxjHJDx2pdM7hMn/RJCFQLimc7XV6oi/ZJCVj0bNICblATwrKwARYEulo/L4z5CqjQ1GvaZFHrMrbVZ3WgwsHyLcBTh0nm/cOHnDjno+C/QZOV6OCV1mxLWs4y0ejmCQ4zCvyluADZ98/OnVkYtUxLQwRCR8L+F0F1msxYL4VTVv3vRMfaERG43oht0TT/mO1Vgl7Jv4H7tXiH1n+Y/douUgSrrf0qZeYxbHq4IcYBdoOOrl1feB9lnUJcJDExAvkQzbf2p7+UpvQxy1uaSmYE8yJfY4jO/CFW3gfQJSM9xGNh0XqB5OIPJ03O4aprDZPev4Eyr+NWol6e010GOclK3S4vmr6S7p+VgcvdshyLE0ft8T1SjjAfW9jtXvbNQeIBThKkVcCPT+w5rw9hE00wfvMFoBp8HBR86TDTBodtLr6h35CDYAlVNDsp3DNAiEUDCcIZ7KxShEKRrriT+ByD4FEnLCzhMMIYp3fcdhqdm6ntu2Dpf/jePGQ4+O3cNuwNKqUMZKXx9f6Nk45L1YliIXihlGywUdW5D0QjE1WFNZS7MCcpAJhhjEMg+auZRTy5fxhFoghO1sfnABkIoI2IXb5+kW4sYFxMSU8/q8xfWyX4ELtbs3gbmlo9KLOyc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
